Integrated API to get gameToken and getResult.
tienping/orvar pull request #3
Opened 2019-10-02 10:24 UTC by akifarhan

Bug: API result need to fix image sent for score<6.

2019-10-03 03:13 UTC, tienping commented on app/containers/GamesPage/index.js
> +            this.props.dispatch(getGameToken());
```
if (globalScope.token) {
  this.props.dispatch(getGameToken());
}
```

2019-10-03 03:13 UTC, tienping commented on app/containers/GamesPage/index.js
> +            this.props.dispatch(getGameToken());
need to handle the case that token is receive from takePocket

2019-10-03 03:24 UTC, tienping requested changes

2019-10-03 03:24 UTC, tienping commented on app/containers/GamesPage/index.js
> +        };
wrap the payload inside perfectPairGame, because we might have diff payload for each game, so let's wrap everything in the game itself

2019-10-03 03:24 UTC, tienping commented on app/containers/GamesPage/saga.js
> +        const response = yield call(apiRequest, '/xmas/game', 'put', payload);
```
const response = yield call(apiRequest, '/xmas/game', 'put', JSON.stringify(action.payload));
```

2019-10-07 10:12 UTC, r0lodex reviewed
to remember the css `autofill`

2019-10-07 10:12 UTC, r0lodex commented on app/global-styles.scss
> +}
👍

2019-10-08 04:18 UTC, merged